### ISSUE TITLE
Warning MSB3270

### ISSUE THREAD

**Issue by CRC32EX** [tabrath/BinaryEncoding#2]
I'm installed your library from NuGet.
Version is `1.3.0`
![image](https://cloud.githubusercontent.com/assets/25629617/25811568/ab2ba284-344e-11e7-8597-62144f925b36.png)

This warning message was shown when i choose platform `Any CPU`.
![image](https://cloud.githubusercontent.com/assets/25629617/25811387/13585ed4-344e-11e7-90f1-a483dd81a2b3.png)
![image](https://cloud.githubusercontent.com/assets/25629617/25811246/92562ae6-344d-11e7-9a99-87e03a96941c.png)

when i choose platform `x64`, message was disappear.

could you fix this warning message?
i want to use `Any CPU`. nothing warning.

thanks.

**Comment by tabrath** [comment]
Ah, I will take a look at it in a couple of hours. Thanks for reporting the issue!

**Comment by CRC32EX** [comment]
thank you!
warning message was gone away!

**Comment by tabrath** [comment]
@CRC32EX The package now targets AnyCPU, not x64. v1.3.4 is now on nuget. At least I don't get the warning anymore..
