### ISSUE TITLE
Use Span<T>

### ISSUE THREAD

**Issue by tabrath** [tabrath/BinaryEncoding#5]
The new [Span<T>](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md) type could provide some optimizations for exactly this library.

**Comment by hanabi1224** [comment]
@tabrath This is super cool improvement to have!  I just created https://github.com/tabrath/BinaryEncoding/pull/26 to help fix travis ci build on mono for net452 in https://github.com/tabrath/BinaryEncoding/pull/14  Hope it can be merged and released soon

**Comment by tabrath** [comment]
I'm so glad you fixed the build issues. Will release a new version as soon as #14 is merged.
